query FindWht($condition: WhtConditionInput) {
  findWht(condition: $condition) {
    id
    recordDate
    title
    textContents {
      id
      name
      text
    }
    imageContents {
      id
      name
      path
    }
  }
}
