// Code generated by SQLBoiler 4.2.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package sqlboilermodel

import "testing"

func TestUpsert(t *testing.T) {
	t.Run("ContentImages", testContentImagesUpsert)

	t.Run("ContentTexts", testContentTextsUpsert)

	t.Run("Migrations", testMigrationsUpsert)

	t.Run("WHTS", testWHTSUpsert)
}
