// Code generated by SQLBoiler 4.2.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package boiled

var TableNames = struct {
	Migration string
	WHT       string
}{
	Migration: "migration",
	WHT:       "wht",
}
