output   = "adapter/gateway/sqlboilermodel"
pkgname  = "sqlboilermodel"

[psql]
  host   = "localhost"
  port   = 11112
  dbname = "whtdbtest"
  user   = "postgres"
  pass   = "yuckyjuice"
  sslmode= "disable"
